"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_controller_1 = require("../controllers/user.controller");
const validation_middleware_1 = require("../middleware/validation.middleware");
const user_types_1 = require("../types/user.types");
const router = (0, express_1.Router)();
router.get('/profile', user_controller_1.getProfile);
router.post('/hobbies', (0, validation_middleware_1.validateBody)(user_types_1.updateUserHobbiesSchema), user_controller_1.updateUserHobbies);
exports.default = router;
