export const AVAILABLE_HOBBIES = [
  'Reading',
  'Writing',
  'Photography',
  'Cooking',
  'Baking',
  'Gardening',
  'Painting',
  'Drawing',
  'Sculpting',
  'Knitting',
  'Crocheting',
  'Sewing',
  'Woodworking',
  'Metalworking',
  'Pottery',
  'Jewelry Making',
  'Origami',
  'Calligraphy',
  'Dancing',
  'Singing',
  'Playing Musical Instruments',
  'Hiking',
  'Camping',
  'Fishing',
  'Swimming',
  'Cycling',
  'Running',
  'Yoga',
  'Meditation',
  'Chess',
  'Board Games',
  'Video Games',
  'Collecting',
  'Bird Watching',
  'Astronomy',
  'Genealogy',
  'Travel',
  'Language Learning',
  'Coding',
  'DIY Projects',
  'Volunteering',
  'Blogging',
  'Podcasting',
  'Film Making',
  'Acting',
  'Magic',
  'Juggling',
  'Rock Climbing',
  'Surfing',
  'Skiing',
  'Snowboarding'
] as const;

export type Hobby = typeof AVAILABLE_HOBBIES[number];
